name: test
on:
  push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello"
      - name: create a comment in Issues.
        uses: actions/github-script@v7
        with:
          script: |

            github.rest.issues.createComment({
              owner: "manlga",
              repo: "test_actions",
              issue_number: 1,
              body: "¿Have you tried to add an issue with that number?"
            })
