name: test
on:
  push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello"
      - name: create a comment in Issues.
        use: actions/github-script@v7
        with:
          script: |

          github.rest.issues.createComment({
            owner: ManlGa,
            repo: test_actions,
            issue_number: 0,
            body: Not a single issue detected
          })
