name: Trigger when running the workflow manually
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: says_hello
        run: echo "This workflow has been manually runned"